# Generated by Django 4.1.8 on 2023-05-23 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('state', models.CharField(db_index=True, max_length=100, verbose_name='Штат')),
                ('zip_index', models.CharField(db_index=True, max_length=10, verbose_name='Почтовый индекс')),
                ('lat', models.CharField(db_index=True, max_length=20, verbose_name='Широта')),
                ('lng', models.CharField(db_index=True, max_length=20, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000, message='Максимальный вес груза 1000'), django.core.validators.MinValueValidator(1, message='Минимальный вес груза 1')], verbose_name='Вес груза')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('delivery_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_where', to='api.location')),
                ('pick_up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wherefrom', to='api.location')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('[1-9][0-9]{3}[A-Z]$', message='Формат номера: число от 1000 до 9999 плюс одна латинская буква в конце')], verbose_name='Автомобильный номер')),
                ('load_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000, message='Максимальный вес груза 1000'), django.core.validators.MinValueValidator(1, message='Минимальный вес груза 1')], verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='where_car', to='api.location')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('pick_up', 'delivery_to'), name='unique_pick_up_delivery_to', violation_error_message='Одинаковое местоположения груза и доставки'),
        ),
    ]
