# Generated by Django 4.1.8 on 2023-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(max_length=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Штат'),
        ),
    ]
